/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Navigation: typeof import('./components/Navigation.vue')['default']
    Particles: typeof import('./components/particles.vue')['default']
    Projects: typeof import('./components/Projects.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skills: typeof import('./components/skills.vue')['default']
  }
}
